( + 3 7 )
( * 4 5 )
( - 12 7 )
( / 40 8 )
( % 9 4 )
( = 10 10 )
( = 7 8 )
( < 5 10 )
( > 20 10 )
( <= 10 10 )
( >= 12 12 )
( SET x 20 )
( + x 5 )
( SET y ( * x 2 ) )
( BEGIN ( * 5 2 ) ( + 3 4 ) )
( CAR ( CONS 10 20 ) )
( CDR ( CONS 10 20 ) )
( DEFINE doubleNum ( num ) ( * num 2 ) )
( doubleNum 7 )
( DEFINE addTwoNums ( a b) ( + a b) )
( addTwoNums 1 2)
( WHILE ( < x 30 ) ( SET x ( + x 1 ) ) )
( LIST? ( CONS 1 2 ) )
( NUMBER? 100 )
( SYMBOL? x )
( SYMBOL? 10 )
( DEFINE square ( num ) ( * num num ) )
( square 5 )
( DEFINE cube ( num ) ( * num ( square num ) ) )
( cube 3 )
( null? ( ) )
( null? 7 )
( DEFINE factorial ( n )
    ( IF ( = n 1 )
        1
        ( * n ( factorial ( - n 1 ) ) )
    )
)
( factorial 5 )
